---
- hosts: strato.sphere.us
  tasks:
    - name: oVirt Authentication
      ovirt_auth:
        url: https://strato.sphere.us/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "B@ndito0317"

    - ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: present
        template: CentOS_7_Generic
        cluster: "Cluster01"
        name: "ansible_test.sphere.us"
        description: "Test deployment with Ansible"
        operating_system: rhel_7x64            
        memory_guaranteed: 1024MiB
        memory_max: 1024MiB    
        cpu_cores: 1 
        nics:
          - name: eth1
            profile_name: ovirtmgmt
            interface: virtio
        cloud-init:
          nic_boot_protocol: static
          nic_ip_address: 10.128.10.101
          nic_netmask: 255.255.255.0
          nic_gateway: 10.128.10.1
          nic_name: eth1
          nic_on_boot: true
          host_name: ansible_test.sphere.us
                
    - name: Always revoke the SSO token
      ovirt_auth: 
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
        
