---
- hosts: strato.sphere.us
  tasks:
    - name: oVirt Authentication
      ovirt_auth:
        url: https://strato.sphere.us/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "B@ndito0317"
