---
- hosts: strato.sphere.us
  tasks:
    - name: oVirt Authentication
      ovirt_auth:
        url: https://strato.sphere.us/ovirt-engine/api
        username: admin@internal
        ca_file: /etc/pki/ovirt-engine/ca.pem
        password: "B@ndito0317"

    - ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: stopped
        name: awx1.sphere.us

    - name: Always revoke the SSO token
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
